### ISSUE TITLE
TRAISIERCPP generates the same STT table every time

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/TRAISIERCPP#1]
It seems that TRAISIERCPP does not use `std::random_device` and `std::mt19337` corretly, because it generates exactly the same result across all replicates.

I think the issue might be linked to this: https://stackoverflow.com/questions/41489979/random-integers-from-a-function-always-return-the-same-number-why

Perhaps we need to change the
```c++
   std::random_device rd;
   std::mt19937 rndgen(rd());
``` 
things to
```c++
    static std::random_device rd; 
    static std::mt19937 rndgen(rd());
```
?

**Comment by thijsjanzen** [comment]
Perhaps. 
In any case, I'm planning to replace the C++ random number generator with R generated random numbers, in order to be able to compare output between R and C++. 
However, I will take a look.

**Comment by EvoLandEco** [comment]
> Perhaps. In any case, I'm planning to replace the C++ random number generator with R generated random numbers, in order to be able to compare output between R and C++. However, I will take a look.

Good to know about this. Declaring static RNGs does generate different results in one run, but still generates the same series of results across different runs called by R. It would be nice to be able to change random seed directly in R.
